#!/usr/bin/env python3
"""Repository production-readiness reviewer powered by Ollama.

This script scans text files in a repository, asks an Ollama model to review each
file, caches results in a memory file, and writes an aggregated tasks list.
"""

import argparse
import datetime as dt
import hashlib
import os
import re
import sys
from pathlib import Path
from xml.parsers.expat import model
from ollama import Client
import json
from jsonschema import validate, ValidationError

IGNORE_DIRS = {
    ".git",
    ".hg",
    ".svn",
    "__pycache__",
    "node_modules",
    ".venv",
    "venv",
    "dist",
    "build",
    ".idea",
    ".vscode",
    ".code_workspace",
    ".meta"
}


file_types = {}
with open("Data/FileTypes.json", "r", encoding='utf-8') as file:
    file_types = json.load(file)

UNKNOWN_FILE_TYPE = "Unknown"

# Files generated by this script and excluded from subsequent reviews.
MEMORY_FILE = ".repo_review_memory.md"
TASKS_FILE = "PRODUCTION_TASKS.md"
FINAL_FILE = "FINAL_REVIEW.md"

JSON_SCHEMA_PER_FILE = """
{
  "type": "object",
  "properties": {
    "relativePath": { "type": "string" },
    "description": { "type": "string" },
    "status": { "type": "string" },

    "requiredTasks": {
      "type": "object",
      "properties": {
        "taskTitle": { "type": "string" },
        "taskDescription": { "type": "string" },
        "importance": { "type": "string" }
      }
    },

    "testsRequired": {
      "type": "object",
      "properties": {
        "testTitle": { "type": "string" },
        "testDescription": { "type": "string" },
        "importance": { "type": "string" }
      }
    },

    "risks": {
      "type": "object",
      "properties": {
        "riskTitle": { "type": "string" },
        "riskDescription": { "type": "string" },
        "riskChance": { "type": "string" }
      }
    },

    "errorObject": {
      "type": "object",
      "properties": {
        "relativePath": { "type": "string" },
        "error": { "type": "string", "enum": ["invalid_output"] }
      }
    }
  }
}
"""

JSON_SCHEMA_ERROR = """
{ 
    "relativePath": "{rel_path}",
    "error": "invalid_output" 
}
"""


def generate_tree(root, prefix="", max_depth=4, depth=0):
    if depth > max_depth:
        return ""

    entries = []
    try:
        items = sorted(os.listdir(root))
    except PermissionError:
        return ""

    items = [i for i in items if i not in IGNORE_DIRS]

    for i, name in enumerate(items):
        path = os.path.join(root, name)
        connector = "└── " if i == len(items) - 1 else "├── "
        entries.append(prefix + connector + name)

        if os.path.isdir(path):
            extension = "    " if i == len(items) - 1 else "│   "
            entries.append(generate_tree(path, prefix + extension, max_depth, depth + 1))

    return "\n".join(entries)


def is_probably_binary(path: Path) -> bool:
    """Return True when a file appears to be binary based on null bytes."""
    try:
        # Read only a small prefix for speed; binary detection doesn't require full file scan.
        with path.open("rb") as f:
            chunk = f.read(4096)
        # Null bytes are a practical signal that the file is binary/non-text.
        return b"\x00" in chunk
    except Exception:
        # Fail closed: if the file cannot be read, skip it from LLM processing.
        return True
    
def is_valid_json(s):
    """Returns true if the parameter S is valid JSON"""
    try:
        json.loads(s)
        return True
    except ValueError:
        return False

def validate_against_schema(json_str, schema):
    "Validates is JOSN meets the given schema"
    try:
        data = json.loads(json_str)
        validate(instance=data, schema=schema)
        return True, None
    except (ValueError, ValidationError) as e:
        return False, str(e)

def sha256_text(text: str) -> str:
    """Compute a stable hash for cached review invalidation."""
    return hashlib.sha256(text.encode("utf-8", errors="ignore")).hexdigest()


def read_text_file(path: Path, max_chars: int) -> str:
    """Read a UTF-8 text file and clamp content to max_chars for model input."""
    # Use errors="ignore" so one malformed byte does not abort the whole run.
    data = path.read_text(encoding="utf-8", errors="ignore")
    if len(data) > max_chars:
        # Add a marker so the review output still explains that input was truncated.
        return data[:max_chars] + f"\n\n...[truncated at {max_chars} chars]"
    return data


def list_files(root: Path):
    """Yield non-binary repository files while skipping known noise directories."""
    for dirpath, dirnames, filenames in os.walk(root):
        # Mutating dirnames in-place tells os.walk which folders not to descend into.
        dirnames[:] = [d for d in dirnames if d not in IGNORE_DIRS and not d.startswith(".")]
        for name in filenames:
            p = Path(dirpath) / name
            # Ignore generated output files so they don't feed back into model input.
            if p.name in {MEMORY_FILE, TASKS_FILE}:
                continue
            if p.is_file() and not is_probably_binary(p):
                yield p


def ollama_generate(model: str, prompt: str, host: str) -> str:
    """Send a generate request to Ollama and return plain text response."""
    client = Client(host=host.rstrip("/"))
    payload = client.generate(model=model, prompt=prompt)
    return payload.get("response", "").strip()


def load_memory(memory_path: Path):
    """Load previously reviewed file entries from the memory file."""

    if not memory_path.exists():
        # First run: no cache exists yet.
        return {}
    text = memory_path.read_text(encoding="utf-8", errors="ignore")
    # The memory file stores one HTML-comment wrapped record per reviewed path.
    pattern = re.compile(
        r'<!-- REVIEW_START path="(?P<path>.*?)" hash="(?P<hash>[a-f0-9]+)" reviewed="(?P<reviewed>.*?)" -->\n(?P<body>.*?)\n<!-- REVIEW_END -->',
        re.DOTALL,
    )
    out = {}
    for m in pattern.finditer(text):
        # Key by relative path so cache entries map directly to scanned files.
        out[m.group("path")] = {
            "hash": m.group("hash"),
            "reviewed": m.group("reviewed"),
            "review": m.group("body").strip(),
        }
    return out


def save_memory(memory_path: Path, entries: dict):
    """Persist review cache for incremental future runs."""
    # Keep this file human-readable so cache behavior can be inspected easily.
    lines = [
        "# Repository Review Memory",
        "",
        f"Updated: {dt.datetime.now().isoformat(timespec='seconds')}",
        "",
        "This file is machine-maintained.",
        "",
    ]
    for path in sorted(entries.keys()):
        # Stable sort keeps diffs deterministic between runs.
        e = entries[path]
        lines.append(
            f'<!-- REVIEW_START path="{path}" hash="{e["hash"]}" reviewed="{e["reviewed"]}" -->'
        )
        lines.append(e["review"].strip())
        lines.append("<!-- REVIEW_END -->")
        lines.append("")
    memory_path.write_text("\n".join(lines), encoding="utf-8")

def review_final(model: str, host: str, tree_analysis, file_reviews) -> str:
    """Ask the LLM for a high-level review of the project structure."""
    prompt = f"""You are performing a final production-readiness assessment of a codebase.

You are acting as a senior engineer making a production decision based on the provided inputs.
- Do NOT evaluate, praise, or critique the review itself
- Do NOT comment on writing quality, structure, or completeness of the analysis
- Do NOT provide meta-feedback
- The goal should be for the smallest set of changes possible to make this reposotory functional.
- Ignore long-term improvements
- You MUST refer to the input files provided and base your judgment on the evidence within them and nothing else.

Your ONLY task is to:
- extract signal from the inputs and make a final production-readiness judgment with clear justification.
- Start directly with Final Verdict.
- Do NOT include introductions, summaries, or commentary about the inputs
- Do NOT explain what you are doing
- Do NOT address the user directly

The output should read like an internal engineering report, not a conversation, and must be relivent to the inputs provided.

You will be given:

- A structural analysis of the repository
- File-level review outputs

#Return concise markdown with:
##Final Verdict
One of:
- Ready for Production
- Conditionally Ready
- Not Ready
- 
and a 2-4 sentence justification

## Critical Issues (Must Fix Before Production)
 - Only include issues that would cause failure, instability, or inability to use the system
 - Deduplicated list of blocking issues (with source file references for traceability)
 - Only include items that would realistically cause failure, instability, or major maintainability problems
 
## High Priority Tasks (Important but not strictly blocking)
 - Focus on scalability, maintainability, and correctness
 - Rejected / Deprioritised Findings
 - List items from earlier analysis that should NOT be prioritised
 - Brief reason (e.g. “low impact”, “speculative”, “duplicate”)
 - attach source file references for traceability

## Architectural Concerns
 - Cross-cutting issues affecting multiple modules
 - Design flaws, coupling, unclear boundaries
 - Risk Assessment
 - Key risks if deployed as-is

## Include uncertainty where applicable
 - Suggested Execution Order
 - Ordered list of what should be done first → last
 - Group related tasks where possible

## Uncertain Findings
 - Items that may be issues but lack sufficient evidence
 - Clearly marked as speculative

## Rules:
 - Be critical and selective — do NOT repeat everything from prior analysis
 - Prefer fewer, high-impact items over exhaustive lists
 - Resolve contradictions explicitly
 - If earlier analysis is weak or inconsistent, say so
 - Do NOT assume missing context — call out uncertainty
 - Do NOT remcommend generic best practices, unless explicitly required by evidence or there are signs of deployment intent (e.g. Dockerfile, cloud config, etc.)
### Disagreements with Earlier Analysis
- Where prior findings appear incorrect or overstated
- Why
### Evidence Rules (STRICT)
**Every claim MUST be supported by:**
- explicit findings from file-level analysis, OR
- clear structural evidence from the repository tree
- Focus on structural and logical improvements, not tooling upgrades
- Only recommend tools, frameworks, or patterns if: a clear deficiency exists, AND he recommendation directly resolves it

### If evidence is weak or missing:
- mark the item as "Uncertain"
- do NOT present it as a confirmed issue
- Do NOT invent files, modules, or functionality that were not present in the inputs
- Avoid generic best-practice recommendations unless directly justified by evidence
- Prefer fewer, high-confidence insights over broad or speculative suggestions

### Precision Rules
Every issue must follow:
- Issue
- Evidence
- Impact
- (Optional) Recommendation

Ensure consistent naming of files and components; flag inconsistencies if detected

# Failure Mode Handling
If the input analysis is weak, inconsistent, or insufficient:
- State this clearly
- Reduce confidence in the final verdict
- Do NOT compensate by inventing additional insights

# Evidence Evaluation:
for each claim or issue you identify, explicitly link it to the supporting evidence from the file reviews or structural analysis. 
This is critical for traceability and for users to understand the basis of your conclusions.
If no evidance exists, Claim it as a assumption and reduce priority.
## Each major section must include:
- Confidence: High / Medium / Low
- Based on completeness and consistency of input data

# Inputs:
## Structural Analysis:
{tree_analysis}

## File-Level Reviews:
{file_reviews}"""

    return ollama_generate(model=model, prompt=prompt, host=host)

def review_project_tree(model: str, host: str, repo_structure: str) -> str:
    """Ask the LLM for a high-level review of the project structure."""
    
    prompt = f"""You are performing a high-level review of a project's structure to identify related files and modular boundaries.
    #Return concise markdown with:
    ## Project Overview:
     - Brief summary of overall structure and organization

    ## Modules and File Groups:
    For each module:

    - Name
    - Purpose (inferred)
    - Location (folder path)
    - Files (explicit list or pattern, e.g. src/core/*)
    - Reasoning (why these files are grouped together)
    - Confidence (High / Medium / Low)

    ## Languages and Technologies (Inferred)
     - List languages based on file extensions
     - List frameworks/tools ONLY if strongly implied by structure
     - Confidence (High / Medium / Low)

    ## Structural Patterns and Conventions:
     - Note any clear patterns (e.g. src/ for source code, tests/ for tests, etc.)
     - Note any conventions (e.g. naming patterns, folder organization)
     - Confidence (High / Medium / Low)

    ## Missing Elements:
    - List commonly expected files or directories that are absent (e.g. README, tests/, config files)
    - Only include items relevant to the inferred project type

    ## Risks / Ambiguities
    - What cannot be reliably determined from structure alone
    - Where assumptions may be incorrect

    ## General Observations (Optional and low priority):
    - Broader best-practice suggestions not strictly required for execution
    - May improve maintainability or robustness but are not critical
    - Avoid generic advice unless clearly relevant to the observed structure
    - Avoid advice that would require significant changes without clear evidence of benefit and feasibility

    #Rules:
     - Do NOT assume functionality without structural evidence
     - Prefer "unknown" over guessing
     - Be explicit when confidence is low
     - Focus on grouping files in a way that would make review more effective

#Context:
{repo_structure}
"""
    return ollama_generate(model=model, prompt=prompt, host=host)

def review_file(model: str, host: str, rel_path: str, content: str, repo_structure: str, inital_review: str, file_type_info) -> str:
    """Ask the LLM for a production-readiness review of one file."""

    # Collect information to provide context for the review

    # if the file type is unknown then provide the answers as unknown. 
    # This allows us to handle cases where the file type is not in our database.
    if (UNKNOWN_FILE_TYPE in file_type_info):
        file_type_info = {
            "Encoding": "Unknown",
            "Human Readable": "Unknown",
            "Human Generated": "Unknown",
            "Suggested Role": "Unknown"
        }
    
    if (file_type_info["Encoding"].lower() == "binary"):
        return "Status: Irrelivent\n- Findings: Not Attempted Due to Binary Encoding"
    
    role = file_type_info["Suggested Role"]

    # if ("source code" in file_type_info["Type"].lower()):
    #     # use the source code review prompt,
    #     print("Found Source Code")
    #     # segment based based on logical boundries like functions or classes if exists or practical. 
    #     # else chose blocks of blank lines, or comments blocks. Worst case find a line end idenfiter and use that.
    #     # make sure to include some overlap between the segments to aid the model in maintaining context.
    #     # focus intially is on python, java, C#, c and C++ code.

    # elif ("Document" in file_type_info["Type"].lower()):
    #     # use the document review prompt,
    #     print("Found Document")
    #     # some documetents will need to be converted to a LLM readable foramt, ideally markdown.

    #     # tex docs will be broken up based on thier subsection headers, with some overlap between the sections. Ideally paragrpah breaks.

    #     # word docs and PDFs will be converted to markdown and then broken up based on blank lines, with some overlap between the sections.

    #     # Other file formats will be delt with on a trial basis.

    # elif ("spreadsheet" in file_type_info["Type"].lower()):
    #     # use the spreadsheet review prompt, 
    #     print("Found Spreadsheet")
    #     # this format is going to be tricky and it is a steach goal to be able to handle it well.

    #     # I think for CSV and such we can convert it to pandas dataframe and use a subset of the data to review it.
    
    # elif ("json" in file_type_info["Type"].lower()):
    #     # use the JSON review prompt, 
    #     print("Found JSON")
    #     # Anaylizing JSON is going to be odd. I think it should be handled in the same way as a csv file, but some of the models will not convert.

    # else:
    #     # use the generic review prompt, 
    #     print("Found Generic File Type")

    # Prompt shape is intentionally strict so downstream task extraction is stable.
    print("Reviewing file:", rel_path)
    prompt = f"""
You are performing a production-readiness code review.
Please write this as if you are a senior engineer

#Return concise markdown with:
**Description**: 
 - A brief summary of what this file is and does.

**Relative Path**: 
 - path relative to repo root
 - {rel_path}

**Status**:
 - Ready = safe for production with minor/no changes
 - Needs Work = functional but has design or maintainability issues
 - Critical = unsafe, broken, or likely to fail in production

**Findings**:
 - Only include concrete, specific issues (no generic advice)
 - Avoid repeating common advice unless it is clearly relevant

**Required Tasks**:
 - Only list tasks that are strictly necessary before production
 - Avoid "nice-to-have" suggestions

**Tests Needed**:
 - List only meaningful tests specific to this file
 - If none are needed, say "None"

**Observability / Risk Notes**:
 - Note hidden risks (state, concurrency, performance, IO, etc.)

#Rules:
 - If the file is empty, trivial, or auto-generated, state that explicitly and keep output minimal
 - Do NOT speculate about other files unless explicitly referenced in this file
 - Do NOT attempt to infer full system architecture from this file alone
 - If no issues, the file is empty or this file seems to be machine written, state that clearly.
 - Focus on getting the point accross over elaborating
 - Assume you are talking to a peer, present text in a mater of fact tone, with no complements to the user.

 -- **You MUST return valid JSON only.**

## STRICT RULES:

Do NOT include any text before or after the JSON
Do NOT include markdown formatting
Do NOT include comments
All fields must be present
If unknown, use "unknown" or empty list []
Maximum 10 issues
Maximum 10 risks
Summary must be <= 2 sentences

If you cannot comply, return:
{JSON_SCHEMA_ERROR}

Match output to this Schema:
{JSON_SCHEMA_PER_FILE}

#Context (project structure):
{repo_structure}

#Inital Review of Project Structure:
{inital_review}

#File content:
{content}
"""
    
    output = ollama_generate(model=model, prompt=prompt, host=host)
    # Delegate transport details to the Ollama client wrapper.

    # check if the code is valid JSON, if it is return it, if not try to extract the JSON from the text and validate it, if that fails return an error. This allows us to handle cases where the model includes some extraneous text along with the JSON, or where the model fails to follow instructions and returns invalid JSON.
    if (is_valid_json(output)) :
        # no futher check because the prompt instructs the model to return valid JSON, and if it does not, we will get an error when trying to parse it, which we can catch and handle gracefully.
        return output
    else:
        # if the code isn't JSON then we can try to extract the JSON from the text and validate it, this allows us to handle cases where the model includes some extraneous text along with the JSON, or where the model fails to follow instructions and returns invalid JSON.
        s_index = output.find("{")
        e_index = output.rfind("}")
        if s_index != -1 and e_index != -1 and s_index < e_index:
            json_str = output[s_index : e_index + 1]
            if is_valid_json(json_str):
                # If we can extract a valid JSON object from the output, return that instead of the full output. This allows us to handle cases where the model includes some extraneous text along with the JSON.
                return json_str
        
        # if the prompt was off by a lot and we can't find any JSON at all, then we can skip the repair step and just return the error, because it's likely that the model completely failed to follow instructions and there's no useful information in the output.
        # TODO run another round of generation to try to fix the JSON if the first attempt fails, but only if we can find a substring that looks like JSON. If we can't find any JSON at all, then we can skip this step and just return the error.
        repair_prompt = f"""
        The following output was intended to be JSON but is not valid. 
                Fix the following Text Under the "Input" section to match the required schema.

                # Rules:

                - Do NOT change meaning, DO NOT add or remove any information, except a note that the output was repaired and may be missing information if the JSON was too broken to repair.
                - Only fix structure, missing fields, or invalid formatting
                - Ensure valid JSON output only

                # Schema:
                {JSON_SCHEMA_PER_FILE}

                # Input:
                {output}
                """
        repaired = ollama_generate(model=model, prompt=repair_prompt, host=host)

        # Try one last time to return the JSON prompt, if it still isn't valid JSON, then return an error. 
        # This allows us to handle cases where the model fails to follow instructions and returns invalid JSON
        if is_valid_json(repaired):
            return repaired
        else:
            s_index = output.find("{")
            e_index = output.rfind("}")
        if s_index != -1 and e_index != -1 and s_index < e_index:
            json_str = output[s_index : e_index + 1]
            if is_valid_json(json_str):
                return json_str
        return JSON_SCHEMA_ERROR.format(rel_path=rel_path)





def extract_required_tasks(review_markdown: str, rel_path: str) -> list[str]:
    """Extract required task bullets from model output into normalized todo text."""
    tasks: list[str] = []
    # Track when we are inside the "Required tasks" section of the model output.
    in_required_tasks = False

    for raw_line in review_markdown.splitlines():
        # Normalize whitespace so downstream checks are resilient to formatting noise.
        line = raw_line.strip()
        if not line:
            continue

        # Accept a few formatting variations because model output may differ.
        if line.lower().strip().startswith(
            ("- \"required tasks\"", "required tasks", "**required tasks**", "__required tasks__")
        ):
            in_required_tasks = True
            continue

        if in_required_tasks and re.match(r"^[-*]\s+", line):
            # Normalize bullet markers and attach source file for traceability.
            task = re.sub(r"^[-*]\s+", "", line).strip()
            if task and task.lower() not in {"none", "n/a"}:
                tasks.append(f"[{rel_path}] {task}")
            continue

        if in_required_tasks and (
            line.lower().startswith("- \"tests needed\"")
            or line.lower().startswith("tests needed")
            or re.match(r"^#+\s+", line)
        ):
            # Stop collecting once the next section begins.
            break

    return tasks


def write_tasks(tasks_path: Path, tasks: list[str], processed: int) -> None:
    """Write aggregated required tasks to a markdown file."""
    # Header metadata helps compare runs without opening memory cache details.
    lines = [
        "# Production Tasks",
        "",
        f"Updated: {dt.datetime.now().isoformat(timespec='seconds')}",
        f"Files reviewed: {processed}",
        "",
    ]

    if not tasks:
        # Explicit text avoids an empty file and confirms run completed.
        lines.append("No required tasks identified.")
    else:
        # Preserve order while removing duplicates from repeated model output.
        seen = set()
        deduped: list[str] = []
        for t in tasks:
            if t not in seen:
                seen.add(t)
                deduped.append(t)
        lines.extend(f"- {t}" for t in deduped)

    tasks_path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def build_parser() -> argparse.ArgumentParser:
    """Build command-line parser for the review run."""
    parser = argparse.ArgumentParser(
        description="Review repository files for production readiness with Ollama."
    )
    parser.add_argument("root", nargs="?", default=".", help="Repository root path.")
    # Model and host make it easy to switch local/remote Ollama targets.
    parser.add_argument("--model", default="gemma4:latest", help="Ollama model name.")
    parser.add_argument("--host", default="http://localhost:11434", help="Ollama host URL.")
    parser.add_argument(
        "--max-chars",
        type=int,
        default=12000,
        help="Max file characters passed to model per file.",
    )
    parser.add_argument("--limit", type=int, default=0, help="Max files to review (0 = no limit).")
    parser.add_argument(
        "--force",
        action="store_true",
        help="Ignore cache and re-review all files.",
    )
    return parser


def main() -> int:
    """Run repository scan, LLM reviews, memory updates, and task generation."""
    parser = build_parser()
    # Parse CLI once at startup and then pass args through the workflow.
    args = parser.parse_args()

    # Normalize to an absolute root so all relative paths are consistent.
    root = Path(args.root).resolve()
    if not root.exists() or not root.is_dir():
        print(f"Error: root path is not a directory: {root}", file=sys.stderr)
        return 2

    # Output files live at repository root and are reused between runs.

    # TODO change the folder where the memory and task files are stored to a hidden folder to avoid cluttering the root of the project. 
    # This will also make it easier to ignore them in .gitignore and avoid accidentally committing them to the repository.
    memory_path = root / MEMORY_FILE
    tasks_path = root / TASKS_FILE
    final_review_path = root / FINAL_FILE

    # Load previously generated reviews so unchanged files can be skipped.
    #memory = load_memory(memory_path)
    memory = {} # Start with a blank slate each time.

    # Build a deterministic processing order for reproducible output.
    files = sorted(list_files(root), key=lambda p: str(p.relative_to(root)))
    if args.limit > 0:
        # Useful for quick dry-runs while tuning prompts.
        files = files[: args.limit]

    if not files:
        print("No eligible text files found.")
        write_tasks(tasks_path, [], 0)
        return 0

    all_tasks: list[str] = []
    # Start from existing memory and update only entries that are re-reviewed.
    #updated_entries = dict(memory)
    updated_entries = dict()
    reviewed_count = 0

    # Determine area's of the codebase that are moduals, or are related and should be reviewed together.
    # This is done by prompting the LLM with the data provided.
    inital_review = review_project_tree("Gemma4:latest", args.host, generate_tree(root))

    # Look at the indivual files and determine if they are related to other files, and if so group them together for review. This is done by prompting the LLM with the data provided.
    for file_path in files:
        # find the file extention:
        file_type = file_types.get(Path(file_path).suffix.upper(), UNKNOWN_FILE_TYPE)

        print(file_type)

        # Convert absolute file path into repository-relative key for reporting/cache lookup.
        rel_path = str(file_path.relative_to(root))
        # Read file content with max-size guard before sending it to the model.
        content = read_text_file(file_path, args.max_chars)
        # Hash current content to detect whether this file changed since last run.
        content_hash = sha256_text(content)
        # Pull prior review metadata for this file path (if any).
        cached = memory.get(rel_path)

        # Reuse cached review when content hash is unchanged unless --force is used.
        if not args.force and cached and cached.get("hash") == content_hash:
            review = str(cached.get("review", "")).strip()
        else:
            try:
                # Generate a fresh review when content changed or --force was requested.
                #print(content)
                review = review_file(args.model, args.host, rel_path, content, generate_tree(root), inital_review, file_type)
                #review="{"+review+"}"
                #print(review.text)
                #print(is_valid_json(review))
            except Exception as exc:
                print(f"Review failed for {rel_path}: {exc}", file=sys.stderr)
                # Keep pipeline moving even if one file fails to generate.
                review = "Status: Critical\n- Findings: Review generation failed\n- Required tasks: Investigate Ollama failure\n- Tests needed: N/A"

            # Update cache entry so future runs can skip unchanged files.
            updated_entries[rel_path] = {
                "hash": content_hash,
                "reviewed": dt.datetime.now().isoformat(timespec="seconds"),
                "review": review,
            }

        # Pull task bullets from the generated review into a global task list.
        all_tasks.extend(extract_required_tasks(review, rel_path))
        # Track number of files attempted (cached + fresh) for final summary.
        reviewed_count += 1

    # Persist updated cache first, then write user-facing consolidated task output.
    save_memory(memory_path, updated_entries)
    # TODO the following task may want to be modified moving forward
    write_tasks(tasks_path, all_tasks, reviewed_count)


    # Reviews the memory and Challanges the assumptions made to minimize the the requirments made and ensure the changes have merit.
    finalReview = review_final(args.model, args.host, inital_review, "\n\n".join(e["review"] for e in updated_entries.values()))
    final_review_path.write_text(finalReview, encoding="utf-8")

    print(f"Reviewed {reviewed_count} files.")
    print(f"Updated memory: {memory_path}")
    print(f"Updated tasks: {tasks_path}")
    print(f"Final review: {final_review_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())